<script defer  src="{{asset('/duynguyen/dadtheme/js/vendors.min.js')}}"></script>
<script defer src="{{asset('/duynguyen/dadtheme/js/datatable/pdfmake.min.js')}}"></script> 
<script defer  src="{{asset('/duynguyen/dadtheme/js/datatable/vfs_fonts.js')}}"></script> 
<script defer src="{{asset('/duynguyen/dadtheme/js/datatable/datatables.min.js')}}"></script> 
<script defer src="{{asset('/duynguyen/dadtheme/js/datatable/datatables.buttons.min.js')}}"></script>
<script defer  src="{{asset('/duynguyen/dadtheme/js/datatable/buttons.html5.min.js')}}"></script> 
<script defer src="{{asset('/duynguyen/dadtheme/js/datatable/buttons.print.min.js')}}"></script> 
<script defer  src="{{asset('/duynguyen/dadtheme/js/datatable/buttons.bootstrap.min.js')}}"></script> 
<script defer src="{{asset('/duynguyen/dadtheme/js/datatable/datatables.bootstrap4.min.js')}}"></script>
<script  defer src="{{asset('/duynguyen/dadtheme/js/app-menu.js')}}"></script> 
<script  defer src="{{asset('/duynguyen/dadtheme/js/app.js')}}"></script> 
<script  defer src="{{asset('/duynguyen/dadtheme/js/components.js')}}"></script> 
<script  defe src="{{asset('/duynguyen/dadtheme/js/datatable/datatable.js')}}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>  
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>